# FT16928
ft_right_foot:
  [  9.783212685,  -2.013586241, -12.88889313,  -547.7058531,    13.63845694,  553.2569078,
    -8.36136005,  635.5897028,     3.265175945, -316.3561145,   -13.1279108,  -320.8829537,
   965.2780635,    25.7416107,   944.6598671,     51.44455906,  901.3227417,    57.84203203,
     0.587368545,   9.094609965, -21.02566806,    -5.594062729,  19.97537992,   -3.257906626,
    23.05512801,    0.707780574, -10.42336368,     7.234739381, -12.8788222,    -8.701025383,
    -0.1103296,    -9.483002109,  -0.049418271,   -9.170443693,  -0.279602398,  -9.054286559 ]

ft_right_foot_unload: [1.408549386, 1.856839286, 1.581656669, 1.8740851, 1.765021205, 1.76662793]


# FT15296
ft_left_foot:
  [ 25.71105746,    6.869125365,  69.3145676,  -649.2729324,  -121.6782649,   660.1014053,
   -49.61810405,  761.6407896,    24.6545091,  -379.5262011,    71.52334686, -386.1615378,
   915.7531108,    25.20157601,  986.6599302,    72.1988179,   851.1222733,    34.73184353,
    -1.235366999,  10.8687653,   -20.72378886,   -6.751458544,  21.37220261,   -4.69597486,
    22.26667486,    0.576699627, -12.1869119,     8.491725575, -10.37922687,   -9.909097888,
     0.940336958, -10.87322025,    1.621858908, -11.06130826,    0.905602916, -11.12864922 ]

ft_left_foot_unload: [1.326928711, 1.573461914, 1.423608398, 1.456640625, 1.486450195, 1.672558594]






## FT15293
#ft_left_foot:
#  [ -12.42499108,    5.564376648,  78.06931699, -619.3110347,   -70.30993288,  624.617862,
#    -71.00758051,  718.996815,     32.33377424, -355.2154984,    53.8449889,  -362.8639736,
#    885.3585975,    37.66431555,  882.9519984,    35.48599363,  897.5702447,    21.0827911,
#     -1.380356297,  10.55040132,  -20.08664366,   -5.951496578,  20.73443154,   -4.901632181,
#     21.69885251,    0.892180817, -12.77054077,    8.299095055,  -9.952203249,  -9.46693911,
#      0.907384694, -10.17497833,    1.113899748, -10.40910503,    1.513983791, -11.06592043]
#
#ft_left_foot_unload: [1.920683789, 1.993560938, 1.911882715, 2.225798438, 1.537770996, 1.998324023]

## FT16660
#ft_right_foot:
#  [  -12.61098528,    1.295270116,   57.39623196,   -554.5290259,    -19.26029779,   548.8779928
#   , -70.15612464,  643.2287242,     27.40020837,   -317.2336528,     34.19379456,  -315.88184
#   , 919.2289042,    34.6133993,    894.6842817,      39.81392009,   883.1627657,     35.05895863
#   ,  -1.172478363,   9.178548803,  -19.20131035,     -5.506500408,   20.22853908,    -3.62161643
#   ,  22.53099552,    0.922509189,  -12.17177313,      7.264041366,  -10.80151556,    -8.261884356
#   ,   0.670193994,  -9.839677757,    1.132650746,    -9.272338153,    0.695107455,   -9.245235747]
#
#ft_right_foot_unload: [1.438110352, 1.531567383, 1.573461914, 1.990795898, 1.758764648, 1.948901367]
#
#
## FT16929
#ft_left_foot:
#  [3.123769346,     0.15387474,     -1.567196255,   -530.7323048,   13.93796306,    530.5844295
#  , 22.30893477,    617.3792021,    -14.40833182,   -305.6228905,   -10.69769289,   -307.0129086
#  , 911.9492834,    36.87511781,    897.1920382,    26.47014129,    886.7242944,    8.696484396
#  , 0.497850228,    8.787811841,    -19.82845636,   -4.796782195,   19.31365995,    -4.168939604
#  , 22.45487138,    0.793296449,    -10.92064334,   7.213740257,    -11.70636706,   -7.642389262
#  , -0.021095082,   -9.310716886,   -0.160304039,   -8.974509353,   -0.639360783,   -9.190091158]
#
#ft_left_foot_unload: [2.450024414, 2.795654297, 2.383154297, 2.412158203, 2.391210938, 2.451635742]