x_offset: -0.03
y_offset: 0.015
z_offset: 0.02
roll_offset: 0
pitch_offset: 0
yaw_offset: 0
hip_pitch_offset: 4.99999985454646
period_time: 600
dsp_ratio: 0.2
step_forward_back_ratio: 0.28
foot_height: 0.04
swing_right_left: 0.015
swing_top_down: 0.006
pelvis_offset: 0.9999999922536332
arm_swing_gain: 0.2
balance_hip_roll_gain: 0.3
balance_knee_gain: 0.2
balance_ankle_roll_gain: 0.6
balance_ankle_pitch_gain: 0.6
p_gain: 0
i_gain: 0
d_gain: 0