x_offset: -0.02
y_offset: 0.015
z_offset: 0.02
roll_offset: 0
pitch_offset: 0
yaw_offset: 0
hip_pitch_offset: 7.000000052497138
period_time: 750
dsp_ratio: 0.2
step_forward_back_ratio: 0.28
foot_height: 0.03
swing_right_left: 0.027
swing_top_down: 0.006
pelvis_offset: 1.500000041741303
arm_swing_gain: 0.2
balance_hip_roll_gain: 0.35
balance_knee_gain: 0.25
balance_ankle_roll_gain: 0.7
balance_ankle_pitch_gain: 0.75
p_gain: 0
i_gain: 0
d_gain: 0