head_pan:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
head_tilt:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
l_ank_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
l_ank_roll:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
l_el:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56
l_hip_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
l_hip_roll:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
l_hip_yaw:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
l_knee:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
l_sho_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56
l_sho_roll:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56
r_ank_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
r_ank_roll:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
r_el:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56
r_hip_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
r_hip_roll:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
r_hip_yaw:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
r_knee:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
r_sho_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56
r_sho_roll:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56