r_sho_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
#   shutdown              :  58
#   homing_offset         :  0
#   torque_limit          :  310
   min_position_limit       : 0
   max_position_limit       : 4095
#   goal_torque          : 310
#   goal_velocity        : 0
#   goal_acceleration    : 0
   position_p_gain          : 600
   position_i_gain          : 150
   position_d_gain          : 50
#   velocity_p_gain      : 180
#   velocity_i_gain      : 452
#   indirect_address_1    :       # indirect address
#     1  :                          # start index (1 ~ 256)
#       - present_position            # addr length : 4
#       - present_velocity            # addr length : 4
#       - present_current             # addr length : 2
#       - present_voltage             # addr length : 2
#       - present_temperature         # addr length : 1
   
l_sho_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 600
   position_i_gain          : 150
   position_d_gain          : 50
   
r_sho_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
l_sho_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
r_el :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_el :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
r_hip_yaw :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
l_hip_yaw :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 150
   position_d_gain          : 50
   
r_hip_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_hip_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
r_hip_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_hip_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
r_knee :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_knee :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
r_ank_pitch :  # XM-430
   return_delay_time        :  1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_ank_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
r_ank_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
l_ank_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 800
   position_i_gain          : 0
   position_d_gain          : 0
   
head_pan :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   
head_tilt :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   